<h1 style="color: #e75480; text-align: center; font-weight: bold;">
    🔍👨‍⚕️ Análisis de Factores Asociados al Diagnóstico de ASD
</h1>

In [1]:
# Este bloque corresponde a la verificación del entorno de trabajo y no a una transformación del dataset.
# Muestra la correcta instalación de las librerías necesarias para el análisis de datos.

# Librerías principales utilizadas:
# - pandas: permite la carga, manipulación, limpieza y análisis estructurado de datos en DataFrames.
# - matplotlib: se utiliza para la generación de visualizaciones básicas.
# - seaborn: permite realizar visualizaciones estadísticas más avanzadas y con mejor interpretación visual.

# Adicionalmente, se observan dependencias como numpy y python-dateutil,
# necesarias para el correcto funcionamiento de las librerías principales.

# Este paso asegura que el entorno es reproducible y que todas las herramientas
# requeridas para el análisis están correctamente configuradas.


%pip install pandas matplotlib seaborn

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nicolescobar/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/nicolescobar/Library/Python/3.14/lib/python/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /Users/nicolescobar/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Importación de pandas para el manejo del dataset
# Se utilizará a lo largo del análisis para realizar la carga, limpieza y transformación de los datos
# dentro del pipeline de preparación previo a la visualización en Power BI

import pandas as pd

<h1 style="color: #1f3a5f; text-align: left; font-weight: bold;">
    🧠📊 ¡Vamos a nuestro Dataset!
</h1>

In [3]:
# Carga del dataset principal desde archivo CSV
# Este paso permite incorporar los datos crudos al entorno de análisis
# y constituye el punto de partida del proceso de preparación (ETL)

df = pd.read_csv("Toddler Autism dataset July 2018.csv")

<h1 style="color: #7ed957; text-align: left; font-weight: bold;">
    ✨🧹 ¡Empezamos la limpieza Y..
</h1> <h2 style="color: #b0b0b0; text-align: left; font-weight: bold;">
    ⚙️✨ Transformación del Dataset del dato crudo al dato util 
</h2>

In [4]:
# Inspección inicial del dataset
# Se visualizan las primeras filas para validar la estructura de las variables,
# identificar posibles inconsistencias y comprender la organización general de los datos
# antes de iniciar el proceso de limpieza y transformación

df.head(10)

,Case_No,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age_Mons,Qchat-10-Score,Sex,Ethnicity,Jaundice,Family_mem_with_ASD,Who completed the test,Class/ASD Traits
0,1,0,0,0,0,0,0,1,1,0,1,28,3,f,middle eastern,yes,no,family member,No
1,2,1,1,0,0,0,1,1,0,0,0,36,4,m,White European,yes,no,family member,Yes
2,3,1,0,0,0,0,0,1,1,0,1,36,4,m,middle eastern,yes,no,family member,Yes
3,4,1,1,1,1,1,1,1,1,1,1,24,10,m,Hispanic,no,no,family member,Yes
4,5,1,1,0,1,1,1,1,1,1,1,20,9,f,White European,no,yes,family member,Yes
5,6,1,1,0,0,1,1,1,1,1,1,21,8,m,black,no,no,family member,Yes
6,7,1,0,0,1,1,1,0,0,1,0,33,5,m,asian,yes,no,family member,Yes
7,8,0,1,0,0,1,0,1,1,1,1,33,6,m,asian,yes,no,family member,Yes
8,9,0,0,0,0,0,0,1,0,0,1,36,2,m,asian,no,no,family member,No
9,10,1,1,1,0,1,1,0,1,1,1,22,8,m,south asian,no,no,Health Care Professional,Yes

In [5]:
# Análisis de la estructura del dataset
# Se evalúan tipos de datos, cantidad de registros y presencia de valores nulos
# con el objetivo de identificar posibles problemas de calidad
# que deban abordarse en la fase de limpieza

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case_No                 1054 non-null   int64
 1   A1                      1054 non-null   int64
 2   A2                      1054 non-null   int64
 3   A3                      1054 non-null   int64
 4   A4                      1054 non-null   int64
 5   A5                      1054 non-null   int64
 6   A6                      1054 non-null   int64
 7   A7                      1054 non-null   int64
 8   A8                      1054 non-null   int64
 9   A9                      1054 non-null   int64
 10  A10                     1054 non-null   int64
 11  Age_Mons                1054 non-null   int64
 12  Qchat-10-Score          1054 non-null   int64
 13  Sex                     1054 non-null   str
 14  Ethnicity               1054 non-null   str
 15  Jaundice                1054 non-null   str
 16  Family_mem_with_ASD     1054 non-null   str
 17  Who completed the test  1054 non-null   str
 18  Class/ASD Traits        1054 non-null   str
dtypes: int64(13), str(6)
memory usage: 156.6 KB

In [6]:
# Evaluación de la dimensión del dataset
# Se identifican el número de registros y variables para dimensionar el volumen de información
# y entender el alcance del análisis previo a la transformación

df.shape

(1054, 19)

In [7]:
# Estandarización de los nombres de las variables
# Se normaliza el formato eliminando espacios, unificando a minúsculas y reemplazando "_" por "espacios"
# con el objetivo de garantizar consistencia en la nomenclatura y evitar errores en el manejo del dataset

df.columns = df.columns.str.strip().str.lower().str.replace("_", " ")

In [8]:
# Estandarización de variables categóricas
# Se seleccionan las columnas de tipo texto para aplicar limpieza únicamente sobre estas variables
# y normalizar su formato, evitando inconsistencias en los valores (espacios, mayúsculas/minúsculas)


text_cols = df.select_dtypes(include=['object', 'string']).columns
df[text_cols] = df[text_cols].apply(lambda x: x.str.strip().str.lower())

In [9]:
# Formateo de nombres de variables para presentación
# Se aplica un tratamiento diferenciado: las variables tipo A1, A2, etc. se mantienen en mayúscula
# para preservar su estructura original, mientras que el resto se transforma a un formato más legible
# (reemplazo de "_" por espacios y uso de formato título)



df.columns = [
    col.upper() if col.lower().startswith('a') and col[1:].isdigit()
    else col.replace('_', ' ').title()
    for col in df.columns]

In [10]:
# Eliminación de registros duplicados
# Se asegura la autonomia de cada observación dentro del dataset



df = df.drop_duplicates()

In [11]:
# Evaluación de valores faltantes por variable
# Se cuantifican los valores nulos en cada columna para identificar problemas de completitud



df.isnull().sum()

Case No                   0
A1                        0
A2                        0
A3                        0
A4                        0
A5                        0
A6                        0
A7                        0
A8                        0
A9                        0
A10                       0
Age Mons                  0
Qchat-10-Score            0
Sex                       0
Ethnicity                 0
Jaundice                  0
Family Mem With Asd       0
Who Completed The Test    0
Class/Asd Traits          0
dtype: int64

In [12]:
# Validación posterior a la limpieza
# Se visualizan las primeras filas para verificar la correcta aplicación
# de las transformaciones realizadas y confirmar la consistencia del dataset

df.head()

,Case No,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age Mons,Qchat-10-Score,Sex,Ethnicity,Jaundice,Family Mem With Asd,Who Completed The Test,Class/Asd Traits
0,1,0,0,0,0,0,0,1,1,0,1,28,3,f,middle eastern,yes,no,family member,no
1,2,1,1,0,0,0,1,1,0,0,0,36,4,m,white european,yes,no,family member,yes
2,3,1,0,0,0,0,0,1,1,0,1,36,4,m,middle eastern,yes,no,family member,yes
3,4,1,1,1,1,1,1,1,1,1,1,24,10,m,hispanic,no,no,family member,yes
4,5,1,1,0,1,1,1,1,1,1,1,20,9,f,white european,no,yes,family member,yes

In [13]:
# Estandarización de la variable categórica 'sex'
# Se unifica el formato de los valores convirtiéndolos a mayúsculas

df['Sex'] = df['Sex'].str.upper()

In [14]:
# Transformación de la variable de edad
# Se genera una nueva variable en años completos a partir de la información original
# con el objetivo de facilitar su interpretación y permitir un análisis más claro por grupos etarios

df['Age Years'] = (df['Age Mons'] // 12).astype(int)

In [15]:
# Eliminación de la variable original 'age_mons'
# Una vez transformada la edad a años completos, esta variable resulta redundante
# y se elimina para mantener un dataset más limpio y evitar duplicidad de información

df = df.drop(columns=['Age Mons'])

In [16]:
# Eliminamos la columna 'Qchat-10-Score' y 'Age Mons'
# El dataset recomienda excluirla para evitar posibles sesgos o riesgos en el análisis
# Esto asegura un modelo más limpio y confiable

df = df.drop(columns=['Qchat-10-Score'])

In [17]:
# Guardamos los nombres de las columnas en una lista
# para poder reorganizar el orden del dataset de forma más clara
cols = list(df.columns)

In [18]:
# Quitamos la columna 'age_years' de su posición actual
# para poder ubicarla después en otra parte del dataset
cols.remove('Age Years')

In [19]:
# Definimos la posición donde queremos insertar la variable 'Age Years' despues de la variable 'sex'
idx = cols.index('Sex')

In [20]:

# Insertamos la columna en la nueva posición dentro del dataset
# para mantener un orden más lógico de las variables
cols.insert(idx + 1, 'Age Years')

In [21]:
# Aplicamos el nuevo orden de columnas al dataset
# reorganizando las variables según la estructura definida previamente
df = df[cols]

In [22]:
# Visualizamos las primeras filas del dataset para verificar
# que el reordenamiento de columnas se aplicó correctamente
df.head()

,Case No,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Sex,Age Years,Ethnicity,Jaundice,Family Mem With Asd,Who Completed The Test,Class/Asd Traits
0,1,0,0,0,0,0,0,1,1,0,1,F,2,middle eastern,yes,no,family member,no
1,2,1,1,0,0,0,1,1,0,0,0,M,3,white european,yes,no,family member,yes
2,3,1,0,0,0,0,0,1,1,0,1,M,3,middle eastern,yes,no,family member,yes
3,4,1,1,1,1,1,1,1,1,1,1,M,2,hispanic,no,no,family member,yes
4,5,1,1,0,1,1,1,1,1,1,1,F,1,white european,no,yes,family member,yes

In [23]:
# Estandarizamos la variable 'ethnicity'
# Unificamos el formato eliminando espacios y normalizando a minúsculas
# para evitar inconsistencias en las categorías antes de su análisis
df['Ethnicity'] = df['Ethnicity'].str.strip().str.lower()

In [24]:
# Definición de mapeo para la recategorización de la variable 'ethnicity'
# Se agrupan categorías similares para reducir la fragmentación de los datos
# y facilitar su análisis e interpretación en el dashboard

mapping = {
    'asian': 'asian',
    'south asian': 'asian',
    
    'white european': 'white',
    
    'middle eastern': 'middle.east',
    
    'hispanic': 'latino',
    'latino': 'latino',
    
    'black': 'black',
    
    'native indian': 'other',
    'pacifica': 'other',
    'mixed': 'other',
    'others': 'other'
}

In [25]:
# Aplicación del mapeo a la variable 'ethnicity'
# Se recategorizan los valores según el diccionario definido y
# aquellos no contemplados se asignan a 'other' para evitar valores nulos
# y mantener consistencia en las categorías
df['Ethnicity'] = df['Ethnicity'].map(mapping).fillna('other')

In [26]:

# Validación de categorías en la variable 'ethnicity'
# Se revisan los valores únicos para confirmar que la recategorización
# se aplicó correctamente y que no existen inconsistencias en las categorías
df['Ethnicity'].unique()

<StringArray>
['middle.east', 'white', 'latino', 'black', 'asian', 'other']
Length: 6, dtype: str

In [27]:
# Renombramos las variables A1–A10 a nombres descriptivos
# para hacer más clara la interpretación de cada comportamiento evaluado
# y facilitar su análisis y visualización en el dashboard

df = df.rename(columns={
    'A1': 'Response_To_Name',
    'A2': 'Eye_Contact',
    'A3': 'Pointing_To_Request',
    'A4': 'Pointing_To_Share',
    'A5': 'Pretend_Play',
    'A6': 'Following_Gaze',
    'A7': 'Empathy',
    'A8': 'Language',
    'A9': 'Gestures',
    'A10': 'Attentive_eye_c'
})

In [28]:
# Definimos una lista con las variables de comportamiento
# Estas variables representan los rasgos evaluados en el test
# y se utilizarán para calcular la puntuación total de traits de ASD
cols = [
    'Response_To_Name','Eye_Contact','Pointing_To_Request',
    'Pointing_To_Share','Pretend_Play','Following_Gaze',
    'Empathy','Language','Gestures','Attentive_eye_c'
]
# Visualizamos las primeras filas solo de estas columnas
# Esto facilita enfocarnos en los comportamientos y validar sus valores
df[cols].head()

,Response_To_Name,Eye_Contact,Pointing_To_Request,Pointing_To_Share,Pretend_Play,Following_Gaze,Empathy,Language,Gestures,Attentive_eye_c
0,0,0,0,0,0,0,1,1,0,1
1,1,1,0,0,0,1,1,0,0,0
2,1,0,0,0,0,0,1,1,0,1
3,1,1,1,1,1,1,1,1,1,1
4,1,1,0,1,1,1,1,1,1,1

In [29]:
# Definimos una lista con las variables de comportamiento
# Estas variables corresponden a los indicadores evaluados en el test
# y se utilizarán para analizar y calcular los rasgos asociados al ASD
cols = [
    'Response_To_Name','Eye_Contact','Pointing_To_Request',
    'Pointing_To_Share','Pretend_Play','Following_Gaze',
    'Empathy','Language','Gestures','Attentive_eye_c'
]

In [30]:
# Cálculo de la puntuación total de rasgos por individuo
# Se suman las variables de comportamiento para obtener un score agregado
# que representa la intensidad de rasgos asociados al ASD en cada caso

df['Total_Traits'] = df[cols].sum(axis=1)

In [31]:
# Clasificación del puntaje total de rasgos
# Se segmenta el score en niveles para facilitar su interpretación
df.Total_Traits.head()

0     3
1     4
2     4
3    10
4     9
Name: Total_Traits, dtype: int64

In [32]:
# Se creo una variable categórica basada en el total de rasgos
# y permitir el análisis por categorías de intensidad (low, medium, high)

df['Trait_Level'] = pd.cut(
    df['Total_Traits'],
    bins=[-1,3,6,10],
    labels=['Low','Medium','High']
)

In [33]:
# Visualizamos los primeros registros de la nueva variable 'Trait Level'
# Esto nos permite verificar cómo quedó la clasificación en niveles
# Validamos que la categorización se haya aplicado correctamente

df ['Trait_Level'].head(50)

0        Low
1     Medium
2     Medium
3       High
4       High
5       High
6     Medium
7     Medium
8        Low
9       High
10    Medium
11      High
12       Low
13      High
14       Low
15      High
16       Low
17      High
18       Low
19      High
20      High
21      High
22      High
23      High
24      High
25       Low
26      High
27      High
28      High
29       Low
30       Low
31       Low
32       Low
33       Low
34       Low
35      High
36       Low
37       Low
38       Low
39       Low
40       Low
41       Low
42       Low
43       Low
44       Low
45       Low
46       Low
47       Low
48       Low
49       Low
Name: Trait_Level, dtype: category
Categories (3, str): ['Low' < 'Medium' < 'High']

In [34]:
# Análisis de la relación entre el score de rasgos y la clasificación de ASD
# Se comparan ambas variables para evaluar la coherencia entre el puntaje calculado
# y la variable de diagnóstico, identificando posibles patrones en los datos

df[['Total_Traits', 'Class/Asd Traits']].head(10)

   Total_Traits Class/Asd Traits
0             3               no
1             4              yes
2             4              yes
3            10              yes
4             9              yes
5             8              yes
6             5              yes
7             6              yes
8             2               no
9             8              yes

In [35]:
# Agrupamos los datos por nivel de rasgos (Trait_Level)
# Contamos la frecuencia de cada categoría de autismo dentro de cada nivel
# Esto nos permite analizar cómo se distribuye el diagnóstico según la intensidad de rasgos 
df.groupby('Trait_Level')['Class/Asd Traits'].value_counts()

Trait_Level  Class/Asd Traits
Low          no                  326
Medium       yes                 326
High         yes                 402
Name: count, dtype: int64

In [36]:
# Contamos la frecuencia de cada categoría en la variable de diagnóstico
# Esto nos permite ver cuántos casos son "yes" y cuántos "no"
# Es útil para entender la distribución inicial del dataset

df['Class/Asd Traits'].value_counts()

Class/Asd Traits
yes    728
no     326
Name: count, dtype: int64

In [37]:
# Convertimos la variable de diagnóstico a formato numérico
# Asignamos 1 a "yes" y 0 a "no" para facilitar el análisis
# Esto permite usar la variable en cálculos y modelos

# Contamos la cantidad de casos en cada categoría
# Nos ayuda a entender la distribución del diagnóstico en el dataset

df['ASD'] = df['Class/Asd Traits'].map({'yes':1, 'no':0})
print(df['ASD'].value_counts())

ASD
1    728
0    326
Name: count, dtype: int64

In [38]:
# Configuramos pandas para mostrar todas las columnas del DataFrame
# Esto evita que se oculten columnas cuando el dataset es muy ancho
# Facilita la exploración completa de los datos 

pd.set_option('display.max_columns', None)
df.head()

,Case No,Response_To_Name,Eye_Contact,Pointing_To_Request,Pointing_To_Share,Pretend_Play,Following_Gaze,Empathy,Language,Gestures,Attentive_eye_c,Sex,Age Years,Ethnicity,Jaundice,Family Mem With Asd,Who Completed The Test,Class/Asd Traits,Total_Traits,Trait_Level,ASD
0,1,0,0,0,0,0,0,1,1,0,1,F,2,middle.east,yes,no,family member,no,3,Low,0
1,2,1,1,0,0,0,1,1,0,0,0,M,3,white,yes,no,family member,yes,4,Medium,1
2,3,1,0,0,0,0,0,1,1,0,1,M,3,middle.east,yes,no,family member,yes,4,Medium,1
3,4,1,1,1,1,1,1,1,1,1,1,M,2,latino,no,no,family member,yes,10,High,1
4,5,1,1,0,1,1,1,1,1,1,1,F,1,white,no,yes,family member,yes,9,High,1

In [39]:
# Revisamos el tipo de dato de cada columna
# Esto nos permite entender cómo está estructurada la información
# Es clave para validar que cada variable tenga el formato correcto para el análisis

df.dtypes

Case No                      int64
Response_To_Name             int64
Eye_Contact                  int64
Pointing_To_Request          int64
Pointing_To_Share            int64
Pretend_Play                 int64
Following_Gaze               int64
Empathy                      int64
Language                     int64
Gestures                     int64
Attentive_eye_c              int64
Sex                            str
Age Years                    int64
Ethnicity                      str
Jaundice                       str
Family Mem With Asd            str
Who Completed The Test         str
Class/Asd Traits               str
Total_Traits                 int64
Trait_Level               category
ASD                          int64
dtype: object

In [40]:
# Seleccionamos un subconjunto específico de columnas del dataset
# Incluimos el identificador y las variables de comportamiento relevantes
# Usamos .copy() para trabajar sobre una copia y evitar modificar el dataset original

facts_behaviors= df[[
    'Case No',
    'Response_To_Name',
    'Eye_Contact',
    'Pointing_To_Request',
    'Pointing_To_Share',
    'Pretend_Play',
    'Following_Gaze',
    'Empathy',
    'Language',
    'Gestures',
    'Attentive_eye_c',
   
]].copy()

In [41]:
# Definimos una lista con las variables de comportamiento
# Estas columnas representan los indicadores clave del análisis
# Nos permitirá trabajar de forma organizada y enfocada en los rasgos

cols_comportamientos = [
    'Response_To_Name',
    'Eye_Contact',
    'Pointing_To_Request',
    'Pointing_To_Share',
    'Pretend_Play',
    'Following_Gaze',
    'Empathy',
    'Language',
    'Gestures',
    'Attentive_eye_c'
]

In [42]:
# Definimos la columna identificadora del dataset
# 'Case No' funciona como ID único para cada registro
# Esto nos permite rastrear y organizar cada observación correctamente

id_col = 'Case No'

In [43]:
# Transformamos el dataset de formato ancho a formato largo
# Convertimos múltiples columnas de comportamiento en dos columnas: tipo de comportamiento y valor
# Esto facilita el análisis, visualización y comparación entre variables

df_long = df.melt(
    id_vars=['Case No'],
    value_vars=[
        'Response_To_Name',
        'Eye_Contact',
        'Pointing_To_Request',
        'Pointing_To_Share',
        'Pretend_Play',
        'Following_Gaze',
        'Empathy',
        'Language',
        'Gestures',
        'Attentive_eye_c'
    ],
    var_name='Comportamiento',
    value_name='Valor'
)

In [44]:
# Contamos cuántas veces aparece cada ID en el dataset transformado
# Esto nos permite verificar que cada caso se repite correctamente por cada comportamiento
# Validamos que la transformación a formato largo se hizo bien

df_long['Case No'].value_counts().head()

Case No
1    10
2    10
3    10
4    10
5    10
Name: count, dtype: int64

In [45]:
# Transformamos la tabla de comportamientos a formato largo
# Convertimos las columnas de comportamientos en filas con su respectivo valor
# Esto permite analizar cada comportamiento de forma individual por caso

facts_behaviors = facts_behaviors.melt(id_vars=['Case No'], value_vars=cols_comportamientos, var_name='Comportamiento', value_name='Valor')

In [46]:
# Visualizamos los nombres de todas las columnas del DataFrame
# Esto nos permite revisar la estructura final del dataset
# Útil para validar cambios después de la limpieza y transformación
df.columns

Index(['Case No', 'Response_To_Name', 'Eye_Contact', 'Pointing_To_Request',
       'Pointing_To_Share', 'Pretend_Play', 'Following_Gaze', 'Empathy',
       'Language', 'Gestures', 'Attentive_eye_c', 'Sex', 'Age Years',
       'Ethnicity', 'Jaundice', 'Family Mem With Asd',
       'Who Completed The Test', 'Class/Asd Traits', 'Total_Traits',
       'Trait_Level', 'ASD'],
      dtype='str')

In [47]:
print(facts_behaviors.columns)

Index(['Case No', 'Comportamiento', 'Valor'], dtype='str')

In [48]:
dim_comportamiento = dim_comportamiento = pd.DataFrame({
    'Codigo_Comportamiento': cols_comportamientos
})

In [49]:
# Creamos una tabla de dimensión demográfica
# Seleccionamos variables relevantes del individuo (edad, sexo, etnicidad, etc.)
# Eliminamos duplicados para asegurar un registro único por caso
dim_demographic = df[['Case No','Age Years','Sex','Ethnicity','Jaundice','Family Mem With Asd','Class/Asd Traits','Total_Traits','Trait_Level','ASD']].drop_duplicates()

In [50]:
# Creamos una dimensión con los tipos de personas que completaron el test
# Seleccionamos la columna y eliminamos valores duplicados
# Esto permite analizar quién realiza el test sin redundancia

dim_who_completed_test = df['Who Completed The Test'].drop_duplicates()

In [51]:
# Visualizamos las primeras filas del dataset final
# Esto nos permite validar el resultado después de todo el proceso
# Confirmamos que los datos están limpios, organizados y listos 
df.head()

,Case No,Response_To_Name,Eye_Contact,Pointing_To_Request,Pointing_To_Share,Pretend_Play,Following_Gaze,Empathy,Language,Gestures,Attentive_eye_c,Sex,Age Years,Ethnicity,Jaundice,Family Mem With Asd,Who Completed The Test,Class/Asd Traits,Total_Traits,Trait_Level,ASD
0,1,0,0,0,0,0,0,1,1,0,1,F,2,middle.east,yes,no,family member,no,3,Low,0
1,2,1,1,0,0,0,1,1,0,0,0,M,3,white,yes,no,family member,yes,4,Medium,1
2,3,1,0,0,0,0,0,1,1,0,1,M,3,middle.east,yes,no,family member,yes,4,Medium,1
3,4,1,1,1,1,1,1,1,1,1,1,M,2,latino,no,no,family member,yes,10,High,1
4,5,1,1,0,1,1,1,1,1,1,1,F,1,white,no,yes,family member,yes,9,High,1

<h2 style="color: #d00000; text-align: left; font-weight: bold;">
    ➡️ Datos listos guardamos y seguimos al siguiente paso
</h2>

In [52]:
# Exportamos las tablas finales a archivos CSV
# Guardamos la tabla de hechos y las dimensiones creadas
# Esto permite usar los datos en herramientas de Power BI
# index=False evita guardar el índice como columna adicional

facts_behaviors.to_csv("fact_comportamientos.csv", index=False)
dim_demographic.to_csv("dim_demographicc.csv", index=False)
dim_comportamiento.to_csv("dim_comportamiento.csv", index=False)
dim_who_completed_test.to_csv("dim_who_completed_test.csv", index=False)